site_name: Syscall Monkey
site_url: https://syscallmonkey.github.io/
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.top
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
plugins:
  - search

nav:
  - Home: index.md
  - Getting Started: getting-started.md
